"use client";

import { useState } from "react";
import type { MentorApplication, MentorRank, MentoringMatch, PublicPilotAccount } from "@/lib/pilot-store";

type Pilot = Pick<PublicPilotAccount, "id" | "name" | "pilotNumber" | "email">;
const levels: Array<{ value: MentorRank; label: string; multiplier: string }> = [
  { value: "new", label: "New Mentor", multiplier: "1.25×" },
  { value: "developing", label: "Developing Mentor", multiplier: "1.5×" },
  { value: "experienced", label: "Experienced Mentor", multiplier: "2×" },
];

async function change(body: Record<string, unknown>) {
  const response = await fetch("/api/staff/mentoring", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const result = await response.json() as { ok?: boolean; error?: string };
  if (!response.ok || !result.ok) throw new Error(result.error ?? "Unable to update mentoring.");
}

export function MentoringCentre({ mentors, learners, matches, applications, pilots }: { mentors: Pilot[]; learners: Pilot[]; matches: MentoringMatch[]; applications: MentorApplication[]; pilots: Pilot[] }) {
  const [mentorPilotId, setMentorPilotId] = useState(mentors[0]?.id ?? "");
  const [learnerPilotId, setLearnerPilotId] = useState(learners[0]?.id ?? "");
  const [goal, setGoal] = useState("");
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [levelsByApplication, setLevelsByApplication] = useState<Record<string, MentorRank>>({});
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const pilot = (id: string) => pilots.find((item) => item.id === id);
  const levelFor = (application: MentorApplication) => levelsByApplication[application.id] ?? application.mentorRank ?? "new";
  async function run(body: Record<string, unknown>) { setBusy(true); setMessage(""); try { await change(body); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update mentoring."); setBusy(false); } }
  const pending = applications.filter((application) => application.status === "pending");
  const approved = applications.filter((application) => application.status === "approved" && application.mentorRank);

  return <section className="career-grid">
    <article className="career-card career-card-wide"><div className="career-card-head"><div><span>COACHING OVERSIGHT</span><h2>Mentor flight reviews</h2></div><a href="/staff/mentoring/reviews">Open assessment queue →</a></div><p>Review submitted Ember coaching notes, update a learner’s Rookie, Developing, or Experienced level, and award a positive flight-specific VA/Tier Point bonus when appropriate.</p></article>
    <article className="career-card career-card-wide"><div className="career-card-head"><div><span>MENTOR APPLICATIONS</span><h2>Review mentor requests</h2></div></div><p>Only staff can approve a mentor or choose their level. The level sets the reward: New Mentor 1.25×, Developing Mentor 1.5×, Experienced Mentor 2×.</p>{pending.length ? <div className="staff-module-list">{pending.map((application) => { const applicant = pilot(application.pilotId); const selected = levelFor(application); return <div key={application.id}><strong>{applicant?.name ?? "Unknown pilot"} · {applicant?.pilotNumber ?? ""}</strong><small>Requested {new Date(application.requestedAt).toLocaleDateString("en-GB")} · {application.requestNote}</small><form onSubmit={(event) => { event.preventDefault(); run({ action: "review", applicationId: application.id, status: "approved", mentorRank: selected }); }}><select value={selected} onChange={(event) => setLevelsByApplication((current) => ({ ...current, [application.id]: event.target.value as MentorRank }))}>{levels.map((level) => <option key={level.value} value={level.value}>{level.label} · {level.multiplier}</option>)}</select><button disabled={busy}>Approve mentor</button><button type="button" disabled={busy} onClick={() => run({ action: "review", applicationId: application.id, status: "declined" })}>Decline</button></form></div>; })}</div> : <p className="career-feedback">No mentor requests are waiting for review.</p>}</article>

    <article className="career-card career-card-wide"><div className="career-card-head"><div><span>APPROVED MENTORS</span><h2>Mentoring levels</h2></div></div><p>Change a level whenever sustained, staff-observed mentoring progress warrants it. The safety limits apply at every level.</p>{approved.length ? <div className="staff-module-list">{approved.map((application) => { const applicant = pilot(application.pilotId); const selected = levelFor(application); return <div key={application.id}><strong>{applicant?.name ?? "Unknown pilot"} · {application.mentorRank ? levels.find((level) => level.value === application.mentorRank)?.label : ""}</strong><small>Current eligible-flight reward: {application.mentorRank ? levels.find((level) => level.value === application.mentorRank)?.multiplier : ""} standard VA and Tier Points.</small><form onSubmit={(event) => { event.preventDefault(); run({ action: "level", pilotId: application.pilotId, mentorRank: selected }); }}><select value={selected} onChange={(event) => setLevelsByApplication((current) => ({ ...current, [application.id]: event.target.value as MentorRank }))}>{levels.map((level) => <option key={level.value} value={level.value}>{level.label} · {level.multiplier}</option>)}</select><button disabled={busy || selected === application.mentorRank}>Save level</button></form></div>; })}</div> : <p className="career-feedback">Approved mentors will appear here after staff review.</p>}</article>

    <article className="career-card career-card-wide"><div className="career-card-head"><div><span>STAFF-CONTROLLED MATCHING</span><h2>Create mentoring match</h2></div></div><p>Only approved mentors can be matched. Each match lasts 30 days; a mentor can support up to three pilots and receives the chosen level only on four eligible accepted Ember flights per calendar month.</p><div className="staff-training-form"><select value={mentorPilotId} onChange={(event) => setMentorPilotId(event.target.value)}><option value="">Choose approved mentor</option>{mentors.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.pilotNumber}</option>)}</select><select value={learnerPilotId} onChange={(event) => setLearnerPilotId(event.target.value)}><option value="">Choose learner</option>{learners.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.pilotNumber}</option>)}</select><input value={goal} onChange={(event) => setGoal(event.target.value)} placeholder="Shared goal, e.g. first long-haul briefing" maxLength={500} /><button className="career-button" disabled={busy || !mentorPilotId || !learnerPilotId} onClick={() => run({ action: "create", mentorPilotId, learnerPilotId, goal })}>Create match</button></div>{message ? <p className="career-feedback error" role="alert">{message}</p> : null}{!mentors.length || !learners.length ? <p className="career-feedback">A match needs one approved mentor and one pilot who requested support.</p> : null}</article>

    <article className="career-card career-card-wide"><div className="career-card-head"><div><span>MENTORING RECORDS</span><h2>Active &amp; completed matches</h2></div></div>{matches.length ? <div className="staff-module-list">{matches.map((match) => { const mentor = pilot(match.mentorPilotId); const learner = pilot(match.learnerPilotId); const active = match.status === "active" && Date.parse(match.expiresAt) > Date.now(); return <div key={match.id}><strong>{mentor?.name ?? "Unknown mentor"} → {learner?.name ?? "Unknown learner"}</strong><small>{match.status} · goal: {match.goal} · expires {new Date(match.expiresAt).toLocaleDateString("en-GB")}</small>{match.progressNotes.map((note) => <small key={note.id}>{new Date(note.createdAt).toLocaleDateString("en-GB")} · {note.authorName}: {note.note}</small>)}{active ? <form onSubmit={(event) => { event.preventDefault(); run({ action: "progress", matchId: match.id, note: notes[match.id] ?? "" }); }}><input value={notes[match.id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [match.id]: event.target.value }))} placeholder="Record a check-in or progress update" maxLength={1000} /><button disabled={busy}>Add check-in</button><button type="button" disabled={busy} onClick={() => run({ action: "end", matchId: match.id, status: "completed" })}>Complete</button><button type="button" disabled={busy} onClick={() => run({ action: "end", matchId: match.id, status: "cancelled" })}>End</button></form> : null}</div>; })}</div> : <p>No mentoring matches yet.</p>}</article>
  </section>;
}
