"use client";

import { useState } from "react";

type Review = { id: string; mentorName: string; learnerName: string; flight: string; metrics: string; approach: string; descentRate: string; overall: string; mentorNote: string; createdAt: string; staffReviewedAt: string | null; experienceLevel: "rookie" | "developing" | "experienced" | null; bonusPercent: number | null; bonusVaPoints: number | null; bonusTierPoints: number | null };
const words = (value: string) => value.replaceAll("_", " ");

export function MentoringReviewCentre({ reviews }: { reviews: Review[] }) {
  const [levels, setLevels] = useState<Record<string, Review["experienceLevel"]>>({});
  const [bonuses, setBonuses] = useState<Record<string, number>>({});
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  async function assess(review: Review) { setBusy(true); setMessage(""); try { const response = await fetch("/api/staff/mentoring-reviews", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ reviewId: review.id, experienceLevel: levels[review.id] ?? "rookie", bonusPercent: bonuses[review.id] ?? 0 }) }); const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error ?? "Unable to save staff assessment."); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save staff assessment."); setBusy(false); } }
  return <section className="career-grid"><article className="career-card career-card-wide"><div className="career-card-head"><div><span>STAFF ASSESSMENT</span><h2>Mentor flight reviews</h2></div></div><p>These are coaching records, not disciplinary reports. Set the learner’s current experience level and optionally grant a one-time positive bonus from the already accepted Ember PIREP. Nothing here can deduct points.</p>{message ? <p className="career-feedback error">{message}</p> : null}{reviews.length ? <div className="staff-module-list">{reviews.map((review) => { const level = levels[review.id] ?? review.experienceLevel ?? "rookie"; const bonus = bonuses[review.id] ?? review.bonusPercent ?? 0; return <div key={review.id}><strong>{review.learnerName} · {review.flight}</strong><small>Mentor: {review.mentorName} · {review.metrics} · submitted {new Date(review.createdAt).toLocaleDateString("en-GB")}</small><small>Approach: {words(review.approach)} · descent: {words(review.descentRate)} · overall: {words(review.overall)}</small><small>Mentor note: {review.mentorNote}</small>{review.staffReviewedAt ? <small>Assessed as {words(review.experienceLevel ?? "rookie")} · {review.bonusPercent}% bonus · +{review.bonusVaPoints ?? 0} VA / +{review.bonusTierPoints ?? 0} Tier Points</small> : <form onSubmit={(event) => { event.preventDefault(); assess(review); }}><select value={level} onChange={(event) => setLevels((current) => ({ ...current, [review.id]: event.target.value as Review["experienceLevel"] }))}><option value="rookie">Rookie pilot</option><option value="developing">Developing pilot</option><option value="experienced">Experienced pilot</option></select><select value={bonus} onChange={(event) => setBonuses((current) => ({ ...current, [review.id]: Number(event.target.value) }))}><option value={0}>No extra points</option><option value={5}>+5% VA and Tier Points</option><option value={10}>+10% VA and Tier Points</option><option value={25}>+25% VA and Tier Points</option></select><button disabled={busy}>Record staff assessment</button></form>}</div>; })}</div> : <p>No mentor flight reviews have been submitted.</p>}</article></section>;
}
