"use client";

import { useState } from "react";

type Flight = { id: string; pilotId: string; learnerName: string; flightNumber: string; from: string; to: string; aircraft: string; completedAt: string; blockMinutes: number; distanceNm: number; fuelUsedKg: number | null; landingFpm: number | null; status: string };
type LiveFlight = { learnerName: string; flightNumber: string; from: string; to: string; aircraft: string; startedAt: string; distanceNm: number; fuelUsedKg: number | null; altitudeFt: number | null; groundSpeedKt: number | null; verticalSpeedFpm: number | null };

const labels = (value: string) => value.replaceAll("_", " ");

export function MentoringFlightDesk({ flights, liveFlights, reviewedFlightIds }: { flights: Flight[]; liveFlights: LiveFlight[]; reviewedFlightIds: string[] }) {
  const available = flights.filter((flight) => !reviewedFlightIds.includes(flight.id));
  const [pirepId, setPirepId] = useState(available[0]?.id ?? "");
  const [approach, setApproach] = useState<"within_parameters" | "too_high" | "too_low" | "unstable" | "not_observed">("within_parameters");
  const [descentRate, setDescentRate] = useState<"within_parameters" | "high" | "low" | "not_observed">("within_parameters");
  const [overall, setOverall] = useState<"progressing" | "needs_coaching" | "ready_for_next_step">("progressing");
  const [mentorNote, setMentorNote] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  async function submit() { setBusy(true); setMessage(""); try { const response = await fetch("/api/pilot/mentoring-reviews", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ pirepId, approach, descentRate, overall, mentorNote }) }); const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error ?? "Unable to submit mentoring review."); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to submit mentoring review."); setBusy(false); } }
  return <section className="career-grid">
    <article className="career-card career-card-wide career-module career-module-mentoring"><div className="career-card-head"><div><span>EMBER · READ-ONLY MENTOR VIEW</span><h2>Active learner flights</h2></div></div><p>These live values are visible only while you have an active staff-created match. You can observe and coach; you cannot change a learner’s flight, PIREP, or points.</p>{liveFlights.length ? <div className="career-record-grid">{liveFlights.map((flight) => <div key={`${flight.learnerName}-${flight.flightNumber}`}><strong>{flight.learnerName} · {flight.flightNumber}</strong><span>{flight.from} → {flight.to} · {flight.aircraft}</span><small>{flight.distanceNm.toLocaleString()} NM · fuel burn {flight.fuelUsedKg == null ? "—" : `${flight.fuelUsedKg.toLocaleString()} kg`} · {flight.altitudeFt == null ? "telemetry waiting" : `${flight.altitudeFt.toLocaleString()} ft / ${flight.groundSpeedKt ?? "—"} kt`} · vertical {flight.verticalSpeedFpm ?? "—"} fpm</small></div>)}</div> : <p>No current Ember session is available for your matched pilots.</p>}</article>
    <article className="career-card career-card-wide"><div className="career-card-head"><div><span>COMPLETED EMBER FLIGHTS</span><h2>Coaching record</h2></div></div><p>Use observed telemetry as a coaching aid, not as a disciplinary score. Mentoring notes never reduce a pilot’s flight credit, VA Points, or Tier Points. One coaching record can be submitted per mentor every 24 hours, with a 12-hour minimum for the same mentor–learner pairing.</p>{flights.length ? <div className="staff-module-list">{flights.slice(0, 12).map((flight) => <div key={flight.id}><strong>{flight.learnerName} · {flight.flightNumber} · {flight.from} → {flight.to}</strong><small>{Math.floor(flight.blockMinutes / 60)}h {String(flight.blockMinutes % 60).padStart(2, "0")}m · {Math.round(flight.distanceNm).toLocaleString()} NM · fuel {flight.fuelUsedKg == null ? "—" : `${flight.fuelUsedKg.toLocaleString()} kg`} · landing {flight.landingFpm == null ? "—" : `${flight.landingFpm} fpm`} · {labels(flight.status)}</small></div>)}</div> : <p>No Ember flight records are available yet.</p>}</article>
    <article className="career-card career-card-wide"><div className="career-card-head"><div><span>MENTOR COACHING NOTE</span><h2>Submit a flight observation</h2></div></div>{available.length ? <div className="staff-training-action"><select value={pirepId} onChange={(event) => setPirepId(event.target.value)}>{available.map((flight) => <option key={flight.id} value={flight.id}>{flight.learnerName} · {flight.flightNumber} · {flight.from} → {flight.to}</option>)}</select><div><label>Approach <select value={approach} onChange={(event) => setApproach(event.target.value as typeof approach)}><option value="within_parameters">Within agreed parameters</option><option value="too_high">Too high</option><option value="too_low">Too low</option><option value="unstable">Unstable</option><option value="not_observed">Not observed</option></select></label><label>Descent rate <select value={descentRate} onChange={(event) => setDescentRate(event.target.value as typeof descentRate)}><option value="within_parameters">Within agreed parameters</option><option value="high">High descent rate</option><option value="low">Low descent rate</option><option value="not_observed">Not observed</option></select></label><label>Overall <select value={overall} onChange={(event) => setOverall(event.target.value as typeof overall)}><option value="progressing">Progressing</option><option value="needs_coaching">Needs coaching</option><option value="ready_for_next_step">Ready for next step</option></select></label></div><textarea value={mentorNote} onChange={(event) => setMentorNote(event.target.value)} placeholder="Describe what you observed, what was done well, and one constructive next action." maxLength={2000} /><button className="career-button" disabled={busy || !pirepId} onClick={submit}>Send to staff review</button>{message ? <p className="career-feedback error">{message}</p> : null}</div> : <p>Every available Ember flight has already been reviewed, or there are no completed Ember flights yet.</p>}</article>
  </section>;
}
