import Link from "next/link";
import type { ActiveCareerRotation } from "@/lib/career-experience";
import type { CareerRotationChoice, CareerRotationProgress } from "@/lib/career-paths";
import { cancelCareerRotationAction, startCareerRotationAction } from "../career-actions";
import styles from "./CareerRotation.module.css";

function bookingHref(leg: { from: string; to: string }) { return `/book?from=${encodeURIComponent(leg.from)}&to=${encodeURIComponent(leg.to)}`; }

export function CareerRotation({ activeRotation, progress, choices }: { activeRotation: ActiveCareerRotation | null; progress: CareerRotationProgress | null; choices: CareerRotationChoice[] }) {
  return <article className={`career-card career-card-wide ${styles.card}`}>
    <div className="career-card-head"><div><span>CAREER ROTATION · OPTIONAL</span><h2>{activeRotation ? activeRotation.title : "Choose your next rotation"}</h2></div>{activeRotation ? <form action={cancelCareerRotationAction}><button className={styles.cancel}>End rotation</button></form> : null}</div>
    {activeRotation && progress ? <><p>{activeRotation.description} Progress is calculated only from accepted BAV PIREPs recorded after you started this rotation.</p><div className="career-progress"><i style={{ width: `${Math.round((progress.completed / progress.total) * 100)}%` }} /></div><p><strong>{progress.completed} / {progress.total} sectors completed.</strong> {progress.complete ? "Rotation complete — excellent work. Your flight records remain the sole source of truth for all awards and credit." : progress.nextLeg ? <>Next: {progress.nextLeg.flightNumber} · {progress.nextLeg.from} → {progress.nextLeg.to} · <Link href={bookingHref(progress.nextLeg)}>Review flight →</Link></> : null}</p><ol className={styles.legs}>{activeRotation.legs.map((leg, index) => <li key={`${leg.routeId}-${index}`} className={progress.completedLegIndexes.includes(index) ? styles.complete : ""}><strong>{progress.completedLegIndexes.includes(index) ? "Completed" : `Sector ${index + 1}`}</strong><span>{leg.flightNumber} · {leg.from} → {leg.to} · {leg.aircraft}</span></li>)}</ol></> : <><p>Rotations are small, flexible multi-flight goals built from the live BAV network. Starting one never books a flight, changes your roster, or creates points, rank or qualification credit.</p>{choices.length ? <div className={styles.choices}>{choices.map((choice) => <section key={choice.id}><strong>{choice.title}</strong><span>{choice.description}</span><small>{choice.legs.map((leg) => `${leg.flightNumber} ${leg.from}–${leg.to}`).join(" · ")}</small><form action={startCareerRotationAction}><input type="hidden" name="rotationId" value={choice.id} /><button className="career-button">Start rotation</button></form></section>)}</div> : <p className={styles.empty}>There are not enough currently bookable, eligible services from your home hub to form a rotation today. The live schedule remains available to browse.</p>}</>}
  </article>;
}
